name: Run Telegram Bot
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install python-telegram-bot
          nohup python3 forwarder_bot.py &